repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.33.0
      hooks:
          - id: eslint
    # export python requirements
    - repo: https://github.com/pdm-project/pdm
      rev: 2.4.2
      hooks:
        - id: pdm-export
          # command arguments, e.g.:
          args: ['-p', 'backend', '-o', 'backend/requirements.txt', '--without-hashes', '--production']
          files: ^backend/pdm.lock$
        - id: pdm-export
          # command arguments, e.g.:
          args: ['-p', 'backend', '-o', 'backend/requirements-dev.txt', '--without-hashes', '--dev']
          files: ^backend/pdm.lock$
