version: '3'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "5432:5432"
    # volumes:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo:
    image: mongo:5
    # command: --serviceExecutor adaptive
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", 'echo "db.getMongo()" | mongo --norc --quiet --host=mongo:27017']
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: "./backend/api"
    ports:
      - "8080:5000"
    volumes:
      - ./backend/api:/app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - SQL_HOST
      - SQL_PORT
      - SQL_USER
      - SQL_PASSWORD
      - SQL_DB
  web:
    build: "./client"
    ports:
      - "80:3000"
    volumes:
      - "./client:/app"
  rabbitmq:
    image: rabbitmq:3.9
