version: '3'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", 'echo "db.getMongo()" | mongosh --norc --quiet --host=mongo:27017']
      interval: 10s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
  api:
    build: "./backend"
    ports:
      - "8080:5000"
    volumes:
      - ./backend/:/app
      - backendvenv:/app/.venv
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - SQL_HOST
      - SQL_PORT
      - SQL_USER
      - SQL_PASSWORD
      - SQL_DB
  web:
    build: "./client"
    ports:
      - "80:3000"
    volumes:
      - "./client:/app"
volumes:
  backendvenv:
