version: '3'
services:
  api:
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/scripts:/app/scripts
      - ./backend/tests:/app/tests
    environment:
      - FLASK_DEBUG=1
  api_worker:
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/scripts:/app/scripts
      - ./backend/tests:/app/tests
  periodiq:
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/scripts:/app/scripts
      - ./backend/tests:/app/tests
    deploy:
      resources:
        limits:
          memory: 512M
  ml_worker_cpu:
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/scripts:/app/scripts
      - ./backend/tests:/app/tests
    deploy:
      resources:
        limits:
          memory: 2G
  web:
    volumes:
      - "./client/src:/app/src"
      - "./client/.env:/app/.env"
